title: Mrunal Padalkar # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  GSSoC'21 • Web Developer • Student • Member of RAIT Alumni Association • Member of RAIT ACM Student Chapter • Community Catalyst at DSCRAIT • University Of Mumbai 
  <br><br>
  Currently, I m enrolled in B.Tech (Computer Engineering) Program at the University of Mumbai.
  I am a web developer with robust problem-solving skills and proven experience in creating and designing web Applications in a test-driven environment.
  So far I have JavaScript, HTML, CSS, Python, Bootstrap, React.JS, and Git/Github under my belt.

  I've started learning Node.JS, MongoDB, and Express.JS. I'm still enthusiastically grabbing onto any other programming languages, frameworks, or principles I can integrate into the coding web in my head.

  I continue to build skills in Cloud Computing, Flutter, and open-source.

  I am seeking web development opportunities and would love to connect with you! 
  <br><br>
  <a href="https://www.linkedin.com/in/mrunalpadalkar/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
